// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQOb98mKNd8fyU77Z2IB6RK-DbdTcZ4JY',
    appId: '1:466805262752:web:0f7cca4c3acd12f87cbcc5',
    messagingSenderId: '466805262752',
    projectId: 'hrtimeplace',
    authDomain: 'hrtimeplace.firebaseapp.com',
    databaseURL: 'https://hrtimeplace.firebaseio.com',
    storageBucket: 'hrtimeplace.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBr7S-DUAoyfIoon_TC52_kET7Zq68lggU',
    appId: '1:466805262752:android:9f944c67396d37cb7cbcc5',
    messagingSenderId: '466805262752',
    projectId: 'hrtimeplace',
    databaseURL: 'https://hrtimeplace.firebaseio.com',
    storageBucket: 'hrtimeplace.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmXrBGKwdJ69OrdF6D7mhQXX4py-KooSA',
    appId: '1:466805262752:ios:0cc5cf3cb6d18e667cbcc5',
    messagingSenderId: '466805262752',
    projectId: 'hrtimeplace',
    databaseURL: 'https://hrtimeplace.firebaseio.com',
    storageBucket: 'hrtimeplace.appspot.com',
    iosBundleId: 'com.hr2o.scheduler.ai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmXrBGKwdJ69OrdF6D7mhQXX4py-KooSA',
    appId: '1:466805262752:ios:0cc5cf3cb6d18e667cbcc5',
    messagingSenderId: '466805262752',
    projectId: 'hrtimeplace',
    databaseURL: 'https://hrtimeplace.firebaseio.com',
    storageBucket: 'hrtimeplace.appspot.com',
    iosBundleId: 'com.hr2o.scheduler.ai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQOb98mKNd8fyU77Z2IB6RK-DbdTcZ4JY',
    appId: '1:466805262752:web:0f7cca4c3acd12f87cbcc5',
    messagingSenderId: '466805262752',
    projectId: 'hrtimeplace',
    authDomain: 'hrtimeplace.firebaseapp.com',
    databaseURL: 'https://hrtimeplace.firebaseio.com',
    storageBucket: 'hrtimeplace.appspot.com',
  );
}